-- SQL-скрипт для добавления портов в базу данных калькулятора ставок фрахта

INSERT INTO ports (id, name, country, region) VALUES
-- Порты Балтийского региона
('EETLL', 'Tallinn', 'Estonia', 'Europe'),
('EERGA', 'Riga', 'Latvia', 'Europe'),
('LVVNT', 'Ventspils', 'Latvia', 'Europe'),
('LTKLJ', 'Klaipeda', 'Lithuania', 'Europe'),
('FIHEL', 'Helsinki', 'Finland', 'Europe'),
('FIKOK', 'Kotka', 'Finland', 'Europe'),
('FITKU', 'Turku', 'Finland', 'Europe'),
('SESTU', 'Stockholm', 'Sweden', 'Europe'),
('SEGOT', 'Gothenburg', 'Sweden', 'Europe'),
('SENMN', 'Nynäshamn', 'Sweden', 'Europe'),
('DKCPH', 'Copenhagen', 'Denmark', 'Europe'),
('DKAAR', 'Aarhus', 'Denmark', 'Europe'),
('PLGDN', 'Gdansk', 'Poland', 'Europe'),
('PLGDY', 'Gdynia', 'Poland', 'Europe'),
('DESTP', 'St. Petersburg', 'Russia', 'Europe'),
('RUKGD', 'Kaliningrad', 'Russia', 'Europe'),

-- Основные порты Европы
('NLRTM', 'Rotterdam', 'Netherlands', 'Europe'),
('DEHAM', 'Hamburg', 'Germany', 'Europe'),
('DEBRV', 'Bremerhaven', 'Germany', 'Europe'),
('BEANR', 'Antwerp', 'Belgium', 'Europe'),
('FRLEH', 'Le Havre', 'France', 'Europe'),
('ESVLC', 'Valencia', 'Spain', 'Europe'),
('ESBCN', 'Barcelona', 'Spain', 'Europe'),
('ITGOA', 'Genoa', 'Italy', 'Europe'),
('ITGIT', 'Gioia Tauro', 'Italy', 'Europe'),
('GRPIR', 'Piraeus', 'Greece', 'Europe'),
('TRMER', 'Mersin', 'Turkey', 'Europe'),
('GBFXT', 'Felixstowe', 'United Kingdom', 'Europe'),
('GBLGP', 'London Gateway', 'United Kingdom', 'Europe'),
('GBSOU', 'Southampton', 'United Kingdom', 'Europe'),

-- Ключевые порты Дальнего Востока
('CNSHA', 'Shanghai', 'China', 'Asia'),
('CNSHE', 'Shenzhen', 'China', 'Asia'),
('CNNGB', 'Ningbo', 'China', 'Asia'),
('CNQIN', 'Qingdao', 'China', 'Asia'),
('CNTXG', 'Tianjin', 'China', 'Asia'),
('CNXMN', 'Xiamen', 'China', 'Asia'),
('HKHKG', 'Hong Kong', 'Hong Kong', 'Asia'),
('TWTPE', 'Taipei', 'Taiwan', 'Asia'),
('TWKHH', 'Kaohsiung', 'Taiwan', 'Asia'),
('JPYOK', 'Yokohama', 'Japan', 'Asia'),
('JPTYO', 'Tokyo', 'Japan', 'Asia'),
('JPOSA', 'Osaka', 'Japan', 'Asia'),
('JPNGO', 'Nagoya', 'Japan', 'Asia'),
('JPKOB', 'Kobe', 'Japan', 'Asia'),
('KRPUS', 'Busan', 'South Korea', 'Asia'),
('KRINC', 'Incheon', 'South Korea', 'Asia'),
('SGSIN', 'Singapore', 'Singapore', 'Asia'),
('MYPKG', 'Port Klang', 'Malaysia', 'Asia'),
('MYTPP', 'Tanjung Pelepas', 'Malaysia', 'Asia'),
('IDTPP', 'Tanjung Priok', 'Indonesia', 'Asia'),
('VNSGN', 'Ho Chi Minh City', 'Vietnam', 'Asia'),
('VNHPH', 'Hai Phong', 'Vietnam', 'Asia'),
('THBKK', 'Bangkok', 'Thailand', 'Asia'),
('THLCH', 'Laem Chabang', 'Thailand', 'Asia'),
('INMUN', 'Mumbai', 'India', 'Asia'),
('INMAA', 'Chennai', 'India', 'Asia'),

-- Порты Северной Америки
('USLAX', 'Los Angeles', 'United States', 'North America'),
('USLGB', 'Long Beach', 'United States', 'North America'),
('USNYC', 'New York', 'United States', 'North America'),
('USSAV', 'Savannah', 'United States', 'North America'),
('USHOU', 'Houston', 'United States', 'North America'),
('USORF', 'Norfolk', 'United States', 'North America'),
('USOAK', 'Oakland', 'United States', 'North America'),
('USBAL', 'Baltimore', 'United States', 'North America'),
('USCHS', 'Charleston', 'United States', 'North America'),
('USMIA', 'Miami', 'United States', 'North America'),
('USEWN', 'Seattle', 'United States', 'North America'),
('USTIW', 'Tacoma', 'United States', 'North America'),
('CAMTR', 'Montreal', 'Canada', 'North America'),
('CAVAN', 'Vancouver', 'Canada', 'North America'),
('CAHAL', 'Halifax', 'Canada', 'North America'),
('MXZLO', 'Manzanillo', 'Mexico', 'North America'),
('MXVER', 'Veracruz', 'Mexico', 'North America'),
('PAPTY', 'Panama City', 'Panama', 'North America'),
('PABLB', 'Balboa', 'Panama', 'North America'),

-- Порты Южной Америки
('BRSSZ', 'Santos', 'Brazil', 'South America'),
('BRRIO', 'Rio de Janeiro', 'Brazil', 'South America'),
('BRPNG', 'Paranagua', 'Brazil', 'South America'),
('BRRIG', 'Rio Grande', 'Brazil', 'South America'),
('ARBUE', 'Buenos Aires', 'Argentina', 'South America'),
('CLVAP', 'Valparaiso', 'Chile', 'South America'),
('CLSAI', 'San Antonio', 'Chile', 'South America'),
('COBUN', 'Buenaventura', 'Colombia', 'South America'),
('PECLL', 'Callao', 'Peru', 'South America'),
('ECGYE', 'Guayaquil', 'Ecuador', 'South America'),
('UYMVD', 'Montevideo', 'Uruguay', 'South America'),

-- Порты Австралии и Океании
('AUSYD', 'Sydney', 'Australia', 'Oceania'),
('AUMEL', 'Melbourne', 'Australia', 'Oceania'),
('AUBNE', 'Brisbane', 'Australia', 'Oceania'),
('AUFRE', 'Fremantle', 'Australia', 'Oceania'),
('AUADL', 'Adelaide', 'Australia', 'Oceania'),
('NZAKL', 'Auckland', 'New Zealand', 'Oceania'),
('NZWLG', 'Wellington', 'New Zealand', 'Oceania'),
('NZLYT', 'Lyttelton', 'New Zealand', 'Oceania'),
('NZTIU', 'Timaru', 'New Zealand', 'Oceania'),
('FJSUV', 'Suva', 'Fiji', 'Oceania'),
('PGPOM', 'Port Moresby', 'Papua New Guinea', 'Oceania')
ON CONFLICT (id) DO NOTHING;
